project:
  type: website

site:
  title: "SNR 690 â€” Contemporary Approaches to Quantitative Methods"
  subtitle: "Student projects, lectures, and methods"
  description: "Course materials, week notes, and student projects for SNR 690."
  author:
    name: "Dr. Alejandro Molina-Moctezuma"
  favicon: assets/favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Weeks
        menu:
          - text: Week 01
            href: weeks/week01.qmd
          - text: Week 02
            href: weeks/week02.qmd
          - text: Week 03
            href: weeks/week03.qmd
          - text: Week 04
            href: weeks/week04.qmd
      - text: Projects
        menu:
          - text: Project Home
            href: projects/index.qmd
      - text: Materials
        menu:
          - text: Week 3 questions
            href: materials/Week3questions.qmd
          - text: Week 3 graffiti wall activity
            href: materials/sixq.qmd 
          - text: Answers to Week 3 questions
            href: materials/answersheet_Version5.qmd     
    right:
      - text: Resources
        menu:
          - text: R for Data Science
            href: https://r4ds.hadley.nz/
          - text: Data Science Introduction
            href: https://bookdown.org/jgscott/DSGI/
          - text: SNR 610 Course Book
            href: https://moctezumaii.github.io/SNR610/
      - text: References
        href: references.qmd
      - text: Slideshows
        menu:
          - text: Slides Week 01
            href: slides/slide-Week01.qmd
          - text: Slides Week 02
            href: slides/slides-Week02.qmd
          - text: Slides Week 03
            href: slides/slides-Week03.qmd
          - text: Slides Week 04
            href: slides/slides-Week04.qmd

bibliography: references.bib   # main BibTeX file (place in repo root)

render:
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true






